package box.lilei.box_client.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "AD_BEAN".
 */
@Entity
public class AdBean {

    @Id
    private Long id;
    private Integer adType;
    private String adVideoFile;
    private String adImgFile;
    private String adUrl;
    private String adPath;

    @Generated(hash = 1093384756)
    public AdBean() {
    }

    public AdBean(Long id) {
        this.id = id;
    }

    @Generated(hash = 699129064)
    public AdBean(Long id, Integer adType, String adVideoFile, String adImgFile, String adUrl, String adPath) {
        this.id = id;
        this.adType = adType;
        this.adVideoFile = adVideoFile;
        this.adImgFile = adImgFile;
        this.adUrl = adUrl;
        this.adPath = adPath;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getAdType() {
        return adType;
    }

    public void setAdType(Integer adType) {
        this.adType = adType;
    }

    public String getAdVideoFile() {
        return adVideoFile;
    }

    public void setAdVideoFile(String adVideoFile) {
        this.adVideoFile = adVideoFile;
    }

    public String getAdImgFile() {
        return adImgFile;
    }

    public void setAdImgFile(String adImgFile) {
        this.adImgFile = adImgFile;
    }

    public String getAdUrl() {
        return adUrl;
    }

    public void setAdUrl(String adUrl) {
        this.adUrl = adUrl;
    }

    public String getAdPath() {
        return adPath;
    }

    public void setAdPath(String adPath) {
        this.adPath = adPath;
    }

}
