package com.zhang.box.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhang.box.db.AdBean;
import com.zhang.box.db.GoodsBean;
import com.zhang.box.db.PercentBean;
import com.zhang.box.db.RoadBean;

import com.zhang.box.db.AdBeanDao;
import com.zhang.box.db.GoodsBeanDao;
import com.zhang.box.db.PercentBeanDao;
import com.zhang.box.db.RoadBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig adBeanDaoConfig;
    private final DaoConfig goodsBeanDaoConfig;
    private final DaoConfig percentBeanDaoConfig;
    private final DaoConfig roadBeanDaoConfig;

    private final AdBeanDao adBeanDao;
    private final GoodsBeanDao goodsBeanDao;
    private final PercentBeanDao percentBeanDao;
    private final RoadBeanDao roadBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        adBeanDaoConfig = daoConfigMap.get(AdBeanDao.class).clone();
        adBeanDaoConfig.initIdentityScope(type);

        goodsBeanDaoConfig = daoConfigMap.get(GoodsBeanDao.class).clone();
        goodsBeanDaoConfig.initIdentityScope(type);

        percentBeanDaoConfig = daoConfigMap.get(PercentBeanDao.class).clone();
        percentBeanDaoConfig.initIdentityScope(type);

        roadBeanDaoConfig = daoConfigMap.get(RoadBeanDao.class).clone();
        roadBeanDaoConfig.initIdentityScope(type);

        adBeanDao = new AdBeanDao(adBeanDaoConfig, this);
        goodsBeanDao = new GoodsBeanDao(goodsBeanDaoConfig, this);
        percentBeanDao = new PercentBeanDao(percentBeanDaoConfig, this);
        roadBeanDao = new RoadBeanDao(roadBeanDaoConfig, this);

        registerDao(AdBean.class, adBeanDao);
        registerDao(GoodsBean.class, goodsBeanDao);
        registerDao(PercentBean.class, percentBeanDao);
        registerDao(RoadBean.class, roadBeanDao);
    }
    
    public void clear() {
        adBeanDaoConfig.clearIdentityScope();
        goodsBeanDaoConfig.clearIdentityScope();
        percentBeanDaoConfig.clearIdentityScope();
        roadBeanDaoConfig.clearIdentityScope();
    }

    public AdBeanDao getAdBeanDao() {
        return adBeanDao;
    }

    public GoodsBeanDao getGoodsBeanDao() {
        return goodsBeanDao;
    }

    public PercentBeanDao getPercentBeanDao() {
        return percentBeanDao;
    }

    public RoadBeanDao getRoadBeanDao() {
        return roadBeanDao;
    }

}
